In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
df = pd.read_csv('/content/drive/MyDrive/data_NBI.csv.zip')

/tmp/ipython-input-3717144908.py:1: DtypeWarning: Columns (5,7,8,9,11,12,19,20,23,24,25,29,30,31,33,34,35,39,44,46,47,55,56,57,60,61,64,68,69,75,76,77,78,79,82,84,87,88,89,96,97,98,103,105,107,108,109,114,115,119,120,121,129) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/data_NBI.csv.zip')

In [13]:
df.sample(50)

,X,Y,FID,STFIPS,REGION,ITEM8,ITEM5A,ITEM5B,ITEM5C,ITEM5D,...,DT,WO_2,STAT,SR1,SR2,EXTRA,STATUS,DATE,LONGDD,LATDD
425348,-75.806989,42.495450,425350,36,2,000000003351020,1,4,1,00000,...,,,0,,857,0,AM,403,-75,42
293712,-89.343344,37.234008,293714,17,5,000002305225036,1,4,1,00000,...,,,0,,832,0,MM,503,-89,37
307090,-86.718450,35.839067,315092,47,4,940A2320003,1,4,1,00232,...,,,0,,881,0,ST,309,-86,35
253952,-96.387244,35.857639,251954,40,6,044850000000000,1,4,1,N3720,...,,,1,,193,1,AM,203,-96,35
128435,-90.390097,32.305425,129436,28,4,SA2500000000166,1,5,1,00410,...,,,0,*,990,0,MM,503,-90,32
594286,-93.270992,46.317756,596290,27,5,L5965,1,4,1,00025,...,,,1,,576,1,MM,503,-93,46
470243,-84.872731,41.298433,469245,18,5,1700129,1,4,1,00010,...,,,0,,915,0,AM,1202,-84,41
210452,-120.415364,37.267208,216454,6,9,39C0173,1,4,0,00000,...,,,0,,846,0,AM,1202,-120,37
504200,-90.916667,42.263889,502203,19,7,000000000193530,1,4,1,00000,...,,,0,,659,0,ST,309,-90,42
108381,-87.609194,32.842008,110382,1,4,002034,1,3,1,00069,...,,,0,*,898,0,MM,403,-87,32
420638,-75.691661,41.583194,423640,42,3,000000000020626,1,3,1,00438,...,,,0,,988,0,ST,309,-75,41
387741,-75.622539,39.969600,386743,42,3,000000000010203,1,2,1,00322,...,,,0,,817,0,AM,1202,-75,39
329097,-84.769511,39.699747,329099,39,5,6836267,1,4,1,C0018,...,,,1,,468,1,ST,314,-84,39
482600,-88.644617,41.159322,489602,17,5,000050007311390,1,8,1,170,...,,,1,,510,1,AM,1202,-88,41
222207,-100.643464,36.732547,230209,40,6,242360000000000,1,4,1,6374C,...,,,0,,989,0,MM,603,-100,36
81283,-81.235681,33.839883,74284,45,4,000000000003386,1,3,1,624,...,,,1,,270,1,MM,603,-81,33
270378,-94.261725,37.675625,269380,29,7,28236,1,4,1,00699,...,,,0,,785,0,AM,1202,-94,37
57102,-83.322617,30.859828,56103,13,4,000000018500770,1,5,1,04900,...,,,0,,975,0,ST,309,-83,30
29648,-97.346436,29.665453,30649,48,6,130900053505149,1,1,1,10,...,,,0,*,774,0,MM,403,-97,29
455373,-83.092553,42.859108,457375,26,5,000000000006282,1,4,1,00000,...,,,0,,990,0,ST,309,-83,42
380783,-76.030000,38.671667,385785,24,3,200000T-0007030,1,4,1,00283,...,,,0,*,999,0,ST,309,-76,38
395857,-71.774472,42.868217,396859,33,1,027700940016200,1,3,1,00031,...,,,0,,0795,0,AM,1202,-71,42
132401,-90.810483,35.030619,131402,5,6,0000000000A3617,1,1,1,40,...,,,0,,809,0,MM,403,-90,35
131301,-92.246314,32.509892,136302,22,6,053701580110121,1,3,1,546,...,,,0,,982,0,AM,1202,-92,32
9555,-66.346667,18.100000,13556,72,1,022781,1,3,8,05558,...,,,0,,954,0,ST,309,-66,18
70482,-79.055489,35.185419,67483,37,4,DAPFORBRA0000U2,1,8,0,0,...,,,0,,980,0,ST,312,-79,35
164800,-97.238661,32.771606,165802,48,6,022200ZR0780002,1,5,1,00000,...,,,2,,805,2,MM,403,-97,32
490572,-88.984269,40.156431,491574,17,5,000020005309572,1,8,1,00051,...,,,0,,780,0,AM,1202,-88,40
478477,-87.520306,40.865747,480479,18,5,5600070,1,4,1,3,...,,,0,,0692,0,AM,1202,-87,40
318776,-87.234583,38.833342,310778,18,5,4200109,1,4,1,00000,...,,,0,,770,2,AM,1202,-87,38
290581,-89.600733,36.518828,292583,29,7,1051,1,3,1,000EE,...,,,0,,0713,0,MM,503,-89,36
213080,-120.788819,37.462953,215082,6,9,39C0108,1,4,0,00000,...,,,0,,546,0,AM,1202,-120,37
293076,-89.565000,37.224444,293078,29,7,33058,1,3,8,00055,...,,,0,,992,0,ST,312,-89,37
121632,-89.557472,33.664572,122633,28,4,SA4900000000129,1,4,1,00179,...,,,1,,448,1,AM,303,-89,33
351293,-82.267733,36.537000,349295,47,4,820A3380001,1,4,1,00338,...,,,0,,805,0,ST,309,-82,36
162970,-97.126153,32.779089,164971,48,6,022200C02421003,1,5,1,00000,...,,,0,,896,0,MM,503,-97,32
316012,-87.654181,39.110775,307014,18,5,027670,1,3,1,00154,...,,,0,,781,0,MM,203,-87,39
361648,-80.052419,36.187494,363650,37,4,000000000670070,1,3,1,02016,...,,,0,,945,0,AM,1202,-80,36
419010,-75.283656,41.304858,421012,42,3,000000000030031,1,5,1,00000,...,,,0,,960,0,MM,503,-75,41
38521,-95.399503,30.313725,38522,48,6,121700033811126,1,3,6,00336,...,,,0,*,0840,0,ST,309,-95,30
232994,-98.576633,35.971300,235996,40,6,120540000000000,1,4,1,E0720,...,,,1,,234,1,AM,1202,-98,35
483818,-86.487481,40.388939,476820,18,5,1200014,1,4,2,00217,...,,,0,,963,0,AM,1202,-86,40
492424,-89.666919,42.105497,496426,17,5,000071324409880,1,4,1,00000,...,,,0,,945,0,AM,1202,-89,42
529723,-95.688889,42.130556,531726,19,7,000000000305460,1,4,1,00000,...,,,0,,563,0,ST,309,-95,42
456751,-83.016472,40.831442,456753,39,5,1738747,1,4,1,C0036,...,,,0,,875,0,AM,1202,-83,40
344925,-82.067583,36.194450,350927,47,4,100A6740001,1,4,1,00674,...,,,2,,777,2,ST,309,-82,36
381700,-77.222750,38.884831,379702,51,3,000000000028663,1,1,1,00066,...,,,0,,0620,2,ST,312,-77,38
581472,-116.267817,46.223467,580476,16,0,000000000030805,1,4,0,00000,...,,,0,,479,0,MM,503,-116,46
305451,-87.723783,36.182617,306453,47,4,430A1330001,1,4,1,00133,...,,,0,,834,0,ST,309,-87,36
434084,-77.124003,41.534203,432086,42,3,000000000025075,1,4,0,00000,...,,,0,,702,0,AM,1202,-77,41